- name: 清空数据
  hosts: single_server
  become: true
  tasks:
    - name: 导入配置
      ansible.builtin.import_role:
        name: chainmaker
        tasks_from: single_get_orglist
    - name: 关闭systemd服务
      ansible.builtin.systemd:
        name: "{{ orgid_list[idx] }}-chain"
        state: stopped
        daemon_reload: true
      loop: "{{ orgid_list }}"
      loop_control:
        index_var: idx
    - name: 移除systemd文件
      ansible.builtin.file:
        path: "/etc/systemd/system/{{ item }}-chain.service"
        state: absent
      loop: "{{ orgid_list }}"
    - name: "清空数据"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ workspace.data_save }}"
        - "{{ workspace.run }}"
