- name: 单机部署链
  hosts: single_server
  roles:
    - chainmaker
  become: true
  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg: "{{ ansible_architecture }}"
      tags: debug
    - name: 软件版本检查
      ansible.builtin.import_role:
        name: chainmaker
        tasks_from: check
      tags: [prepare, prepare_check]
    - name: 准备目录
      ansible.builtin.import_role:
        name: chainmaker
        tasks_from: single_prepare_dir
      tags: [prepare, prepare_dir]
    - name: 编译链运行时二进制
      ansible.builtin.import_role:
        name: chainmaker
        tasks_from: compile
      tags: [prepare, prepare_compile]
    - name: 编译证书工具
      ansible.builtin.import_role:
        name: chainmaker
        tasks_from: compile_certstools
      tags: [prepare, prepare_certs_tool]
    - name: 生成证书
      ansible.builtin.import_role:
        name: chainmaker
        tasks_from: gen_crts
      tags: [prepare, prepare_certs]
    - name: 生成运行时配置文件
      ansible.builtin.import_role:
        name: chainmaker
        tasks_from: single_gen_runtime_config
      tags: [prepare, prepare_runtime_config]
    - name: 拷贝运行文件
      ansible.builtin.import_role:
        name: chainmaker
        tasks_from: single_run_prepare
      tags: [prepare, prepare_run]
    - name: 准备Systemd
      ansible.builtin.import_role:
        name: chainmaker
        tasks_from: single_run_systemd
      tags: [prepare, prepare_run_systemd]
    - name: Start
      ansible.builtin.import_role:
        name: chainmaker
        tasks_from: single_start
      tags: [prepare, start]
    - name: Test
      ansible.builtin.import_role:
        name: chainmaker
        tasks_from: test
      tags: [prepare, test]
