- name: 单机部署链
  hosts: single_server
  roles:
    - { role: chainmaker }
    - { role: dev }
  tasks:
    # - name: Test
    #   ansible.builtin.import_role:
    #     name: chainmaker
    #     tasks_from: test
