- name: 创建编译工作目录
  ansible.builtin.file:
    path: "{{ workspace.compile }}"
    state: directory
    mode: 0777
- name: 是否已经编译完成了
  ansible.builtin.stat:
    path: "{{ workspace.compile }}/{{ bin }}{{ chainmaker.new_version }}"
  register: bin_file_stat
- name: GOPATH
  ansible.builtin.import_tasks: gopath.yml
  tags: clone
  when: not bin_file_stat.stat.exists or force
- name: Chainmaker项目clone
  ansible.builtin.git:
    repo: "https://{{ chainmaker.username | urlencode }}:{{ chainmaker.password | urlencode }}@{{ chainmaker.repo }}"
    dest: "{{ workspace.compile }}/{{ chainmaker.name }}{{ chainmaker.new_version }}"
    version: "{{ chainmaker.new_version }}"
    force: true
    depth: 1
    single_branch: true
  tags: clone
- name: 编译脚本拷贝
  ansible.builtin.template:
    src: "compile.{{ chainmaker.new_version }}.sh.j2"
    dest: "{{ workspace.compile }}/{{ chainmaker.name }}{{ chainmaker.new_version }}/compile-upgrade.ansible.sh"
    mode: 0755
    force: true
  tags: [clone]
  when: not bin_file_stat.stat.exists or force
- name: 编译
  ansible.builtin.command: ./compile-upgrade.ansible.sh
  args:
    chdir: "{{ workspace.compile }}/{{ chainmaker.name }}{{ chainmaker.new_version }}"
  register: result
  changed_when: true
  tags: compile_bin
  when: not bin_file_stat.stat.exists or force
