- name: 关闭systemd服务
  ansible.builtin.import_tasks: more_stop.yml
- name: Disable systemd services
  ansible.builtin.import_tasks: more_systemd_disable.yml
- name: 移除systemd文件
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ chainmaker }}.service"
    state: absent
- name: "清空数据"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ workspace.data_save }}"
    - "{{ workspace.run }}"
