- name: 引入组织id变量
  ansible.builtin.import_tasks: single_get_orglist.yml
  tags: systemd_disable
- name: 禁止systemd服务开机启动
  ansible.builtin.systemd:
    name: "{{ item }}-chain.service"
    enabled: false
  loop: "{{ orgid_list }}"
  become: true
  tags: systemd_disable
  failed_when: false
