- name: 部署多机房长安链
  hosts: multroom
  tasks:
    - name: 创建存储目录
      ansible.builtin.import_role:
        name: chainmaker
        tasks_from: more_prepare_dir
    - name: 拷贝运行时文件
      ansible.builtin.import_role:
        name: chainmaker
        tasks_from: more_copy_runtime
    - name: 拷贝配置文件
      ansible.builtin.import_role:
        name: chainmaker
        tasks_from: more_copy_config
    # - name: Debug
    #   ansible.builtin.debug:
    #     msg: "im at {{ idx }}, i am {{ orgid_list[idx] }}, nodeid is {{ nodeid_list[idx] }}"
    #   when: item == inventory_hostname
    #   loop: "{{ groups['multroom'] }}"
    #   loop_control:
    #     index_var: idx
