- name: 重置环境
  hosts: multroom
  become: true
  tasks:
    - name: 停止服务
      ansible.builtin.import_role:
        name: chainmaker
        tasks_from: more_stop.yml
      tags: stop
    - name: 重启服务
      ansible.builtin.import_role:
        name: chainmaker
        tasks_from: more_start.yml
      tags: restart
