- name: 获取节点id, 组织id
  ansible.builtin.import_tasks: get_nodeid.yml
- name: 拷贝配置文件
  vars:
    files:
      - "bc"
      - "log"
      # - "chainmaker"
  # ansible.builtin.debug:
  #   msg:
  #     - "{{ chainmaker.version }}/{{ item.1 }}.tpl.j2"
  #     - "{{ workspace.run }}/{{ crypto_config.host_name + '%d' | format(item.0) }}/{{ item.1 }}.yml"
  ansible.builtin.template:
    src: "{{ chainmaker.version }}/{{ item.1 }}.tpl.j2"
    dest: "{{ workspace.run }}/{{ crypto_config.host_name + '%d' | format(item.0) }}/{{ item.1 }}.yml"
    mode: 0644
  loop: "{{ range(1, crypto_config.count + 1) | product(files) | list }}"
