- name: 创建存储目录
  ansible.builtin.file:
    path: "{{ workspace.data_save }}/{{ item }}"
    state: directory
    mode: 0777
  loop: "{{ org_list }}"
- name: 创建日志目录
  ansible.builtin.file:
    path: "{{ workspace.log_save }}/{{ item }}"
    state: directory
    mode: 0777
  loop: "{{ org_list }}"
- name: 创建运行时目录
  ansible.builtin.file:
    path: "{{ workspace.run }}/{{ item }}"
    state: directory
    mode: 0777
  loop: "{{ org_list }}"
