- name: 组织org_id列表赋值
  ansible.builtin.set_fact:
    orgid_list: "{{ range(1, crypto_config.count + 1) | map('regex_replace', '(.+)', crypto_config.host_name + '\\1') | list }}"
  when: orgid_list is not defined
