# 部署
- name: 关闭服务
  ansible.builtin.import_tasks: single_stop.yml
  tags: restart
- name: 启动systemd服务
  ansible.builtin.systemd:
    name: "{{ orgid_list[idx] }}-chain.service"
    state: restarted
    daemon_reload: true
  loop: "{{ orgid_list }}"
  loop_control:
    index_var: idx
  become: true
  tags: restart
