- name: 创建存储目录
  vars:
    files:
      - "log"
      - "data"
  ansible.builtin.file:
    path: "{{ workspace.data_save }}/{{ item.0 }}/{{ item.1 }}"
    state: directory
    mode: 0777
  loop: "{{ orgid_list | product(files) | list }}"
- name: 创建运行时目录
  ansible.builtin.file:
    path: "{{ workspace.run }}/{{ item }}"
    state: directory
    mode: 0777
  loop: "{{ orgid_list }}"
