- name: 引入组织id变量
  ansible.builtin.import_tasks: single_get_orglist.yml
  tags: systemd_enable
- name: 开机启动systemd服务
  ansible.builtin.systemd:
    name: "{{ item }}-chain.service"
    enabled: true
  loop: "{{ orgid_list }}"
  become: true
  tags: systemd_enable
  when: ansible_architecture != "aarch64"
- name: 开机启动systemd服务
  ansible.builtin.command: "systemctl enable {{ item }}-chain.service"
  loop: "{{ orgid_list }}"
  become: true
  tags: systemd_enable
  when: ansible_architecture == "aarch64"
