- name: 引入组织id变量
  ansible.builtin.import_tasks: single_get_orglist.yml
- name: 打包配置文件
  community.general.archive:
    path:
      - "{{ workspace.run }}/{{ orgid_list[0] }}/bc.yml"
      - "{{ workspace.run }}/{{ orgid_list[0] }}/log.yml"
      - "{{ workspace.run }}/{{ orgid_list[0] }}/chainmaker.yml"
    dest: "/tmp/config.zip"
    mode: 0644
    format: zip
    remove: false
- name: 下载配置文件
  ansible.builtin.fetch:
    src: /tmp/config.zip
    dest: "{{ inventory_dir }}/test/config.zip"
    mode: 0755
    flat: true
- name: 本地解压配置文件
  ansible.builtin.unarchive:
    src: "{{ inventory_dir }}/test/config.zip"
    dest: "{{ inventory_dir }}/test"
  delegate_to: localhost
